apiVersion: v1
kind: Pod
metadata:
  name: gke-datastore
spec:
  serviceAccountName: sa-k8snovice
  containers:
  - name: gke-datastore
    image: ghcr.io/keisukesakasai/work-gke-datastore:latest
    imagePullPolicy: Always
    env:
    - name: PROJECT_ID
      value: "study-work-387200"
    ports:
    - containerPort: 80